### PR TITLE
Uncomment FunctionalSpec TCs & permit /aop-prometheus without auth

### PR DESCRIPTION
**Pull request by aman-agrawal**
Jira : https://devopsmx.atlassian.net/browse/OP-21248
Issue : /aop-prometheus url is asking for auth & hence for gate service, prometheus is unable to fetch metrics
Solution : Permitted url without auth

Jira : https://devopsmx.atlassian.net/browse/OP-20822
Issue : TC is commented as part of CVE project
Solution : Uncommented

### CODE REVIEW

**Review by kirangodishala — APPROVED** [review]
lgtm

**Comment by kirangodishala** [comment]
@aman-agrawal - can you check why the build failed.

**Comment by aman-agrawal** [comment]
> @aman-agrawal - can you check why the build failed.

Build is passing locally. I think it is false alarm, code is compiled against java11 in github action.

**Review by yugaa22 — APPROVED** [review]
Ok

**Pull request merged**
